spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/demoDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootuser
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

contents:
  value: test

jwt:
  secret: "{cipher}81e2e92ef623baa00b6486ddb3895f24ffffade5ae912515e2452aacb410fd0e"
